"""
Report Exporter — v31.0 Smart UX
Exports system information as Markdown or HTML report.
"""

import os
import subprocess
from datetime import datetime
from typing import Dict, Optional


class ReportExporter:
    """Exports system information in Markdown or HTML format."""

    @staticmethod
    def gather_system_info() -> Dict[str, str]:
        """
        Collect all system information for the report.

        Returns:
            Dictionary of system info key-value pairs.
        """
        info = {}
        try:
            info["hostname"] = subprocess.getoutput("hostname").strip()
        except Exception:
            info["hostname"] = "Unknown"

        try:
            info["kernel"] = subprocess.getoutput("uname -r").strip()
        except Exception:
            info["kernel"] = "Unknown"

        try:
            info["fedora_version"] = subprocess.getoutput("cat /etc/fedora-release").strip()
        except Exception:
            info["fedora_version"] = "Unknown"

        try:
            cpu = subprocess.getoutput("lscpu | grep 'Model name' | cut -d: -f2").strip()
            info["cpu"] = cpu if cpu else "Unknown"
        except Exception:
            info["cpu"] = "Unknown"

        try:
            mem = subprocess.getoutput("free -h | awk '/^Mem:/ {print $2 \" total, \" $3 \" used\"}'").strip()
            info["ram"] = mem
        except Exception:
            info["ram"] = "Unknown"

        try:
            disk = subprocess.getoutput("df -h / | awk 'NR==2 {print $3 \"/\" $2 \" (\" $5 \" used)\"}'").strip()
            info["disk_root"] = disk
        except Exception:
            info["disk_root"] = "Unknown"

        try:
            info["uptime"] = subprocess.getoutput("uptime -p").strip()
        except Exception:
            info["uptime"] = "Unknown"

        try:
            if os.path.exists("/sys/class/power_supply/BAT0/capacity"):
                capacity = subprocess.getoutput("cat /sys/class/power_supply/BAT0/capacity").strip()
                status = subprocess.getoutput("cat /sys/class/power_supply/BAT0/status").strip()
                info["battery"] = f"{capacity}% ({status})"
            else:
                info["battery"] = "No battery detected"
        except Exception:
            info["battery"] = "Unknown"

        try:
            info["architecture"] = subprocess.getoutput("uname -m").strip()
        except Exception:
            info["architecture"] = "Unknown"

        try:
            info["desktop"] = os.environ.get("XDG_CURRENT_DESKTOP", "Unknown")
        except Exception:
            info["desktop"] = "Unknown"

        info["report_date"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        return info

    @staticmethod
    def export_markdown(info: Dict[str, str]) -> str:
        """
        Format system info as a Markdown report.

        Args:
            info: Dictionary of system info key-value pairs.

        Returns:
            Formatted Markdown string.
        """
        lines = [
            "# System Report — Loofi Fedora Tweaks",
            "",
            f"**Generated:** {info.get('report_date', 'Unknown')}",
            "",
            "## System Information",
            "",
            "| Property | Value |",
            "|----------|-------|",
        ]

        field_labels = {
            "hostname": "Hostname",
            "kernel": "Kernel",
            "fedora_version": "Fedora Version",
            "cpu": "CPU",
            "ram": "RAM",
            "disk_root": "Disk Usage (/)",
            "uptime": "Uptime",
            "battery": "Battery",
            "architecture": "Architecture",
            "desktop": "Desktop Environment",
        }

        for key, label in field_labels.items():
            value = info.get(key, "Unknown")
            lines.append(f"| {label} | {value} |")

        lines.append("")
        lines.append("---")
        lines.append("*Report generated by Loofi Fedora Tweaks*")
        lines.append("")

        return "\n".join(lines)

    @staticmethod
    def export_html(info: Dict[str, str]) -> str:
        """
        Format system info as a styled HTML report.

        Args:
            info: Dictionary of system info key-value pairs.

        Returns:
            Complete HTML document string.
        """
        field_labels = {
            "hostname": "Hostname",
            "kernel": "Kernel",
            "fedora_version": "Fedora Version",
            "cpu": "CPU",
            "ram": "RAM",
            "disk_root": "Disk Usage (/)",
            "uptime": "Uptime",
            "battery": "Battery",
            "architecture": "Architecture",
            "desktop": "Desktop Environment",
        }

        rows = ""
        for key, label in field_labels.items():
            value = info.get(key, "Unknown")
            rows += f"        <tr><td><b>{label}</b></td><td>{value}</td></tr>\n"

        report_date = info.get("report_date", "Unknown")

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>System Report — Loofi Fedora Tweaks</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
               max-width: 800px; margin: 40px auto; padding: 0 20px;
               background: #0b0e14; color: #e6edf3; }}
        h1 {{ color: #39c5cf; border-bottom: 2px solid #1c2030; padding-bottom: 12px; }}
        table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
        th, td {{ padding: 10px 16px; text-align: left; border-bottom: 1px solid #1c2030; }}
        th {{ background: #1c2030; color: #39c5cf; }}
        tr:hover {{ background: #1c2030; }}
        .footer {{ color: #6c7086; font-size: 0.85em; margin-top: 30px; }}
    </style>
</head>
<body>
    <h1>System Report — Loofi Fedora Tweaks</h1>
    <p><b>Generated:</b> {report_date}</p>
    <h2>System Information</h2>
    <table>
        <tr><th>Property</th><th>Value</th></tr>
{rows}    </table>
    <p class="footer">Report generated by Loofi Fedora Tweaks</p>
</body>
</html>"""

        return html

    @staticmethod
    def save_report(path: str, fmt: str, info: Optional[Dict[str, str]] = None) -> str:
        """
        Generate and save a system report to a file.

        Args:
            path: Output file path.
            fmt: Format — 'markdown' or 'html'.
            info: Optional pre-gathered info dict. If None, gathers fresh info.

        Returns:
            The path of the saved report.
        """
        if info is None:
            info = ReportExporter.gather_system_info()

        if fmt == "html":
            content = ReportExporter.export_html(info)
        else:
            content = ReportExporter.export_markdown(info)

        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

        return path
